/*
 * EmployeeRegistraionForm.java
 * This class provides a GUI for employee registration, allowing users to create new accounts.
 * Author: Praveen Dani
 */

package UI_Package;

import ClassPackage.UserClass;
import javax.swing.JOptionPane;

/**
 * EmployeeRegistraionForm
 * JFrame for registering new HR users (HR Manager or HR Assistant).
 */
public class EmployeeRegistraionForm extends javax.swing.JFrame {

    /**
     * Constructor - Initializes the registration form components.
     */
    public EmployeeRegistraionForm() {
        initComponents();
    }

    /**
     * Initializes the form components and layout.
     * This method is auto-generated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Panel and UI components declaration and initialization
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel(); // Title label
        jLabel2 = new javax.swing.JLabel(); // User ID label
        txtUserID = new javax.swing.JTextField(); // User ID input
        txtPassword = new javax.swing.JPasswordField(); // Password input
        txtConfirmPassword = new javax.swing.JPasswordField(); // Confirm password input
        cmbUserType = new javax.swing.JComboBox<>(); // User type dropdown
        jLabel4 = new javax.swing.JLabel(); // Password label
        jLabel5 = new javax.swing.JLabel(); // Confirm password label
        jLabel6 = new javax.swing.JLabel(); // User type label
        btnRegister = new javax.swing.JButton(); // Register button
        btnHomeScreen = new javax.swing.JButton(); // Go to home screen button

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Set up labels and fields
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // Title font
        jLabel1.setText("Create Account");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14));
        jLabel2.setText("User ID");

        txtUserID.setFont(new java.awt.Font("Segoe UI", 0, 14));
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14));

        txtConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 14));

        cmbUserType.setFont(new java.awt.Font("Segoe UI", 0, 14));
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR Manager", "HR Assistant" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14));
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14));
        jLabel5.setText("Confirm Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14));
        jLabel6.setText("User Type");

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnHomeScreen.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnHomeScreen.setText("Go to Home Screen");
        btnHomeScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeScreenActionPerformed(evt);
            }
        });

        // Layout setup for the panel
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(btnRegister))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbUserType, javax.swing.GroupLayout.Alignment.TRAILING, 0, 205, Short.MAX_VALUE)
                    .addComponent(txtUserID)
                    .addComponent(txtPassword)
                    .addComponent(txtConfirmPassword)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHomeScreen)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnHomeScreen))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        // Layout setup for the frame
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the Register button click event.
     * Validates input fields and attempts to register a new user.
     */
    @SuppressWarnings("deprecation")
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        boolean valid = true; // Flag for input validation

        // Check for empty fields
        if (txtUserID.getText().toString().isEmpty() || txtPassword.getText().toString().isEmpty() ||
            txtConfirmPassword.getText().toString().isEmpty() || cmbUserType.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field can't be blank ",
                    "Register form", JOptionPane.ERROR_MESSAGE);
            valid = false;
        } else {
            // Check password length
            if (txtPassword.getText().toString().length() < 5) {
                JOptionPane.showMessageDialog(null, "Password must have 5 characters ", "Register form",
                        JOptionPane.ERROR_MESSAGE);
                valid = false;
            }
            // Check password match
            else if (!txtPassword.getText().toString().equals(txtConfirmPassword.getText().toString())) {
                JOptionPane.showMessageDialog(null, "Password and confirm password should match",
                        "Employee Registration Form", JOptionPane.ERROR_MESSAGE);
                valid = false;
            }
        }

        // If all validations pass, create new user
        if (valid) {
            String userid = txtUserID.getText();
            String password = txtPassword.getText();
            String userType = cmbUserType.getSelectedItem().toString();

            UserClass newUser = new UserClass(userid, password, userType);

            // Attempt to add new user and show result
            if (newUser.addNewUser()) {
                JOptionPane.showMessageDialog(null, "User Added successfully", "Add a new User",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Sorry! Something went wrong with the application, Will be fixing it soon.",
                        "Add a new User", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * Handles the User ID field action event (not used).
     */
    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // No action required
    }//GEN-LAST:event_txtUserIDActionPerformed

    /**
     * Handles the Home Screen button click event.
     * Navigates to the WelcomeInterface and closes the current form.
     */
    @SuppressWarnings("deprecation")
    private void btnHomeScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeScreenActionPerformed
        WelcomeInterface obj = new WelcomeInterface();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnHomeScreenActionPerformed

    /**
     * Main method to launch the EmployeeRegistraionForm.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistraionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistraionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistraionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistraionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRegistraionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomeScreen; // Button to go to home screen
    private javax.swing.JButton btnRegister; // Button to register new user
    private javax.swing.JComboBox<String> cmbUserType; // Dropdown for user type
    private javax.swing.JLabel jLabel1; // Title label
    private javax.swing.JLabel jLabel2; // User ID label
    private javax.swing.JLabel jLabel4; // Password label
    private javax.swing.JLabel jLabel5; // Confirm password label
    private javax.swing.JLabel jLabel6; // User type label
    private javax.swing.JPanel jPanel1; // Main panel
    private javax.swing.JPasswordField txtConfirmPassword; // Confirm password field
    private javax.swing.JPasswordField txtPassword; // Password field
    private javax.swing.JTextField txtUserID; // User ID field
    // End of variables declaration//GEN-END:variables

}
