/*
 * WelcomeInterface.java
 * This class defines the welcome screen for the Colombo Institute of Studies application.
 * It provides options to create a new user account or go to the login form.
 */

package UI_Package;

/**
 * The WelcomeInterface class displays the main welcome window with options
 * for user registration and login.
 * 
 * @author Praveen Dani
 */
public class WelcomeInterface extends javax.swing.JFrame {

    /**
     * Constructor for WelcomeInterface.
     * Initializes the GUI components.
     */
    public WelcomeInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Panel to hold all components
        jPanel1 = new javax.swing.JPanel();
        // Main welcome label
        jLabel1 = new javax.swing.JLabel();
        // Separator label
        jLabel2 = new javax.swing.JLabel();
        // Label for account creation section
        jLabel3 = new javax.swing.JLabel();
        // Label for login section
        jLabel5 = new javax.swing.JLabel();
        // Button to create a new account
        btnCreateAccount = new javax.swing.JButton();
        // Button to go to login form
        btnGoToLoginForm = new javax.swing.JButton();

        // Set default close operation for the window
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Set font and text for the main welcome label
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText(" Welcome to colombo institute of studies");

        // Set text for the separator label
        jLabel2.setText("========================================================================================");

        // Set font and text for the account creation label
        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Create a New Account for User");

        // Set font and text for the login label
        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setText("User Login");

        // Set font and text for the create account button
        btnCreateAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateAccount.setText("Create New Account");
        // Add action listener for create account button
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        // Set font and text for the login form button
        btnGoToLoginForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGoToLoginForm.setText("Go to Login Form");
        // Add action listener for login form button
        btnGoToLoginForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToLoginFormActionPerformed(evt);
            }
        });

        // Layout configuration for the panel
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCreateAccount))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGoToLoginForm)))
                            .addGap(32, 32, 32)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnCreateAccount))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnGoToLoginForm))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        // Layout configuration for the main frame
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        // Adjusts window size to fit components
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action performed when "Create New Account" button is clicked.
     * Opens the Employee Registration Form and closes the current window.
     */
    @SuppressWarnings("deprecation")
    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
       EmployeeRegistraionForm obj=new EmployeeRegistraionForm();
       obj.show();
       this.dispose();
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    /**
     * Action performed when "Go to Login Form" button is clicked.
     * Opens the Login Form and closes the current window.
     */
    @SuppressWarnings("deprecation")
    private void btnGoToLoginFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToLoginFormActionPerformed
       LoginForm obj=new LoginForm();
       obj.show();
       this.dispose();
    }//GEN-LAST:event_btnGoToLoginFormActionPerformed

    /**
     * Main method to launch the WelcomeInterface window.
     * Sets the Nimbus look and feel if available.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Button for creating a new account
    private javax.swing.JButton btnCreateAccount;
    // Button for going to the login form
    private javax.swing.JButton btnGoToLoginForm;
    // Main welcome label
    private javax.swing.JLabel jLabel1;
    // Separator label
    private javax.swing.JLabel jLabel2;
    // Label for account creation
    private javax.swing.JLabel jLabel3;
    // Label for login
    private javax.swing.JLabel jLabel5;
    // Main panel
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
